
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: team02-w24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjg4MTU5NDI2","is_bot":false,"login":"hyi96","name":""},"headRefName":"Hao-Articles","number":50,"title":"hy - Articles database table created","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-4/pull/50"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-Organization","number":49,"title":"Created Database table for UCSBOrganizations","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-4/pull/49"}]
