
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: team02-w24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOBclbpw","is_bot":false,"login":"hongye-liang","name":""},"headRefName":"Hongye-MenuItemReview-Controller","number":59,"title":"Hongye MenuItemReview controller (get all, post, get, put, and delete)","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-4/pull/59"},{"author":{"id":"U_kgDOBcwKVw","is_bot":false,"login":"JustinZhang809","name":""},"headRefName":"Justin-DiningCommonsMenuItemsTable","number":57,"title":"Added database table for UCSB Dining Commons Menu Items","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-4/pull/57"},{"author":{"id":"MDQ6VXNlcjg4MTU5NDI2","is_bot":false,"login":"hyi96","name":""},"headRefName":"Hao-ArticlesGetAndPost","number":52,"title":"Hao articles get and post","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-4/pull/52"}]
